Update configuration
Lund-Org/cherry pull request #9
Opened 2018-12-21 21:25 UTC by JuMastro

* Add Travis configuraton included codeClimate & tests

* Add .gittatributes

* Add .editorconfig

* Add eslint

Add eslint and plugins (import, node, promise) + standard set
Add .eslintrc.js & .eslintignore

* Add package.json with inital configuration + .lock

* Add CHANGELOG.md

2018-12-21 21:31 UTC, JuMastro commented
# TODO:

## Travis
- Should link to [travis.com](https://travis-ci.com)
- Should set env vars (NPM_API_KEY, NPM_EMAIL & CC_TEST_REPORTER_ID)

CC_TEST_REPORTER_ID can be found from "Analysis > Test coverage" from codeClimate project settings.

## CodeClimate
- Should link to [codeClimate](https://codeclimate.com)

![image](https://user-images.githubusercontent.com/25881035/50364328-e6035e80-056f-11e9-9eea-1420aba99542.png)
![image](https://user-images.githubusercontent.com/25881035/50364305-c835f980-056f-11e9-8a0d-ce166d4bdf62.png)
![image](https://user-images.githubusercontent.com/25881035/50364399-1ba84780-0570-11e9-96ac-1ee96a8c8d33.png)

2018-12-21 21:32 UTC, JuMastro commented
# Important
- Should add branch security, wait for review + travis validation + (codeClimate validation?!)

2018-12-22 02:08 UTC, Mystilund requested changes

2018-12-22 02:08 UTC, FlorianDewulf commented on package.json
> +  "main": "./src/index.js",
wrong

2018-12-22 02:08 UTC, FlorianDewulf commented on .editorconfig
> +root = true
File to delete

2018-12-22 11:41 UTC, JuMastro commented on package.json
> +  "main": "./src/index.js",
It's update to `./src/cherry.js`

2018-12-22 11:41 UTC, JuMastro commented on .editorconfig
> +root = true
This file is now deleted

2018-12-22 17:53 UTC, Mystilund approved these changes

2018-12-22 17:57 UTC, merged